apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::263022081217:role/eks-argocd-karpenter-managed-ondemand"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "team-marble-group"
      "rolearn": "arn:aws:iam::263022081217:role/eks-argocd-karpenter-team-marble-access"
      "username": "team-marble"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::263022081217:role/eks-argocd-karpenter-admin-access"
      "username": "admin"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::263022081217:role/myTeamRole"
      "username": "ahamadmin"
  mapUsers: |
    []
immutable: false
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-06T23:07:17Z"
  labels:
    app.kubernetes.io/created-by: terraform-aws-eks-blueprints
    app.kubernetes.io/managed-by: terraform-aws-eks-blueprints
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7090"
  uid: 28c76f9c-8ec4-4253-b139-9d3f62bbf3f1
